/**
 * Migration runner. Applies the SQL migrations generated by drizzle-kit in
 * `./drizzle` (resolved from process.cwd()) using the migrator that matches
 * the active driver (postgres-js or PGlite).
 *
 * Idempotent: drizzle records applied migrations in `drizzle.__drizzle_migrations`
 * and skips the ones already present. Used by `pnpm db:migrate`, by
 * `instrumentation.ts` on boot (AUTO_MIGRATE) and by the test helpers.
 */
import path from 'node:path';

import { sql } from 'drizzle-orm';
import type { PgliteDatabase } from 'drizzle-orm/pglite';
import type { PostgresJsDatabase } from 'drizzle-orm/postgres-js';

import { dbDriver, getDb, type Db, type Schema } from './index';

export type DbDriver = 'postgres' | 'pglite';

export const MIGRATIONS_FOLDER = 'drizzle';

export type MigrationResult = {
  /** Number of migrations applied by this run (0 when already up to date). */
  applied: number;
  /** Total migrations recorded in the database after the run. */
  total: number;
};

async function countApplied(db: Db): Promise<number> {
  try {
    const rows = await db
      .select({ n: sql<string>`count(*)` })
      .from(sql`drizzle.__drizzle_migrations`);
    return Number(rows[0]?.n ?? 0);
  } catch {
    // The migrations table does not exist yet — nothing has been applied.
    return 0;
  }
}

/** Absolute path to the migrations folder for the current process. */
export function migrationsFolder(): string {
  return path.resolve(process.cwd(), MIGRATIONS_FOLDER);
}

/**
 * Run pending migrations against `db` using the migrator for `driver`.
 * Logs and returns how many migrations were applied.
 */
export async function runMigrations(db: Db, driver: DbDriver, opts: { quiet?: boolean } = {}): Promise<MigrationResult> {
  const folder = migrationsFolder();
  const before = await countApplied(db);

  if (driver === 'postgres') {
    const { migrate } = await import('drizzle-orm/postgres-js/migrator');
    await migrate(db as unknown as PostgresJsDatabase<Schema>, { migrationsFolder: folder });
  } else {
    const { migrate } = await import('drizzle-orm/pglite/migrator');
    await migrate(db as unknown as PgliteDatabase<Schema>, { migrationsFolder: folder });
  }

  const total = await countApplied(db);
  const applied = Math.max(0, total - before);
  if (!opts.quiet) {
    if (applied > 0) {
      console.info(`[db] Kjørte ${applied} migrering(er) (${driver}); totalt ${total}.`);
    } else {
      console.info(`[db] Databasen er oppdatert (${total} migrering(er), ${driver}).`);
    }
  }
  return { applied, total };
}

/**
 * Initialise the database client and, when AUTO_MIGRATE is on, apply pending
 * migrations. Safe to call more than once; only the first call does work.
 */
let readyPromise: Promise<Db> | null = null;

export function ensureDbReady(): Promise<Db> {
  if (!readyPromise) {
    readyPromise = (async () => {
      const { env } = await import('@/env');
      const db = await getDb();
      if (env.AUTO_MIGRATE) {
        const driver = dbDriver() ?? (env.DATABASE_URL ? 'postgres' : 'pglite');
        await runMigrations(db, driver);
      }
      return db;
    })().catch((err) => {
      // Allow a retry on the next call rather than caching the failure forever.
      readyPromise = null;
      throw err;
    });
  }
  return readyPromise;
}
