/**
 * Desken — database schema (PostgreSQL dialect, Drizzle ORM).
 *
 * This file is the shared contract for the whole CMS. Every site-scoped table
 * carries `siteId`. IDs are UUIDs generated by the database. All timestamps are
 * `timestamptz`. Soft deletes use `deletedAt` where a "papirkurv" (trash) makes
 * sense for editors (articles, media).
 *
 * Naming: snake_case in the database, camelCase in TypeScript.
 */
import { relations, sql } from 'drizzle-orm';
import {
  boolean,
  customType,
  date,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  primaryKey,
  real,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  type AnyPgColumn,
} from 'drizzle-orm/pg-core';

import type { ContentDoc } from '@/lib/content/types';
import type { LayoutDoc } from '@/lib/layout/types';
import type { FieldDef, MenuItem, SiteSettings } from '@/lib/validation/site';

/* -------------------------------------------------------------------------- */
/*  Custom column types                                                        */
/* -------------------------------------------------------------------------- */

export const tsvector = customType<{ data: string; driverData: string }>({
  dataType() {
    return 'tsvector';
  },
});

/* -------------------------------------------------------------------------- */
/*  Enums                                                                      */
/* -------------------------------------------------------------------------- */

/**
 * Roles within a site membership.
 *  - admin:       everything, including settings, users, API keys
 *  - editor:      redaktør/vaktsjef: publish, layouts, all content
 *  - journalist:  create and edit all articles, cannot publish
 *  - contributor: freelancer: own drafts only
 *  - viewer:      read-only access to the admin
 */
export const memberRoleEnum = pgEnum('member_role', [
  'admin',
  'editor',
  'journalist',
  'contributor',
  'viewer',
]);
export type MemberRole = (typeof memberRoleEnum.enumValues)[number];

/** Editorial workflow states (Norwegian labels live in i18n). */
export const articleStatusEnum = pgEnum('article_status', [
  'draft', // Utkast
  'in_review', // Til gjennomsyn
  'approved', // Godkjent
  'scheduled', // Planlagt
  'published', // Publisert
  'unpublished', // Avpublisert
  'archived', // Arkivert
]);
export type ArticleStatus = (typeof articleStatusEnum.enumValues)[number];

/** Reader access level. `plus` = behind paywall teaser. */
export const articleAccessEnum = pgEnum('article_access', ['open', 'plus']);
export type ArticleAccess = (typeof articleAccessEnum.enumValues)[number];

export const mediaKindEnum = pgEnum('media_kind', ['image', 'video', 'audio', 'document']);
export type MediaKind = (typeof mediaKindEnum.enumValues)[number];

export const revisionKindEnum = pgEnum('revision_kind', ['autosave', 'manual', 'publish', 'restore']);
export type RevisionKind = (typeof revisionKindEnum.enumValues)[number];

export const authTokenKindEnum = pgEnum('auth_token_kind', [
  'invite',
  'password_reset',
  'email_verify',
  'preview',
]);
export type AuthTokenKind = (typeof authTokenKindEnum.enumValues)[number];

export const liveBlogStatusEnum = pgEnum('live_blog_status', ['draft', 'live', 'ended']);
export type LiveBlogStatus = (typeof liveBlogStatusEnum.enumValues)[number];

export const bylineRoleEnum = pgEnum('byline_role', ['text', 'photo', 'video', 'graphics', 'other']);
export type BylineRole = (typeof bylineRoleEnum.enumValues)[number];

/* -------------------------------------------------------------------------- */
/*  Sites (multi-tenancy)                                                      */
/* -------------------------------------------------------------------------- */

export const sites = pgTable('sites', {
  id: uuid('id').primaryKey().defaultRandom(),
  /** URL-safe identifier, also used as a fallback path prefix in dev. */
  slug: text('slug').notNull().unique(),
  name: text('name').notNull(),
  tagline: text('tagline'),
  /** Hostnames that resolve to this site, e.g. ["elvebyen.no", "www.elvebyen.no"]. */
  domains: text('domains').array().notNull().default(sql`'{}'::text[]`),
  /** 'nb' (bokmål) or 'nn' (nynorsk). */
  locale: text('locale').notNull().default('nb'),
  timezone: text('timezone').notNull().default('Europe/Oslo'),
  /** Typed in src/lib/validation/site.ts (theme, masthead, responsible editor, VVP checklist, ...). */
  settings: jsonb('settings').$type<SiteSettings>().notNull().default(sql`'{}'::jsonb`),
  isActive: boolean('is_active').notNull().default(true),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

/* -------------------------------------------------------------------------- */
/*  Users, memberships, sessions, tokens, API keys                             */
/* -------------------------------------------------------------------------- */

export const users = pgTable(
  'users',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    /** Always stored lower-cased and trimmed. */
    email: text('email').notNull(),
    name: text('name').notNull(),
    /** argon2id hash. Null until an invited user sets a password. */
    passwordHash: text('password_hash'),
    avatarMediaId: uuid('avatar_media_id'),
    /** UI language for the admin: 'nb' | 'nn' | 'en'. */
    locale: text('locale').notNull().default('nb'),
    /** Superadmins bypass site membership checks (installation owners). */
    isSuperadmin: boolean('is_superadmin').notNull().default(false),
    isActive: boolean('is_active').notNull().default(true),
    /** TOTP secret (base32), encrypted at rest with APP_SECRET. */
    totpSecret: text('totp_secret'),
    totpEnabled: boolean('totp_enabled').notNull().default(false),
    emailVerifiedAt: timestamp('email_verified_at', { withTimezone: true }),
    lastLoginAt: timestamp('last_login_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('users_email_idx').on(t.email)],
);

export const memberships = pgTable(
  'memberships',
  {
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    siteId: uuid('site_id')
      .notNull()
      .references(() => sites.id, { onDelete: 'cascade' }),
    role: memberRoleEnum('role').notNull().default('journalist'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.siteId] }), index('memberships_site_idx').on(t.siteId)],
);

export const sessions = pgTable(
  'sessions',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    /** SHA-256 of the opaque cookie token. The raw token is never stored. */
    tokenHash: text('token_hash').notNull(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    /** Whether a second factor was completed for this session. */
    mfaVerified: boolean('mfa_verified').notNull().default(false),
    ip: text('ip'),
    userAgent: text('user_agent'),
    lastSeenAt: timestamp('last_seen_at', { withTimezone: true }).notNull().defaultNow(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('sessions_token_hash_idx').on(t.tokenHash), index('sessions_user_idx').on(t.userId)],
);

export const authTokens = pgTable(
  'auth_tokens',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id').references(() => users.id, { onDelete: 'cascade' }),
    siteId: uuid('site_id').references(() => sites.id, { onDelete: 'cascade' }),
    kind: authTokenKindEnum('kind').notNull(),
    tokenHash: text('token_hash').notNull(),
    /** Free-form payload, e.g. { role: 'editor' } for invites or { articleId } for preview links. */
    meta: jsonb('meta').$type<Record<string, unknown>>().notNull().default(sql`'{}'::jsonb`),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    usedAt: timestamp('used_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('auth_tokens_hash_idx').on(t.tokenHash), index('auth_tokens_user_idx').on(t.userId)],
);

export const apiKeys = pgTable(
  'api_keys',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    siteId: uuid('site_id')
      .notNull()
      .references(() => sites.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    /** First 8 chars of the key, shown in the UI to identify it. */
    keyPrefix: text('key_prefix').notNull(),
    keyHash: text('key_hash').notNull(),
    /** e.g. ['content:read'] — reserved for future write scopes. */
    scopes: text('scopes').array().notNull().default(sql`'{}'::text[]`),
    lastUsedAt: timestamp('last_used_at', { withTimezone: true }),
    createdBy: uuid('created_by').references(() => users.id, { onDelete: 'set null' }),
    revokedAt: timestamp('revoked_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('api_keys_hash_idx').on(t.keyHash), index('api_keys_site_idx').on(t.siteId)],
);

/* -------------------------------------------------------------------------- */
/*  Taxonomy: sections, tags, authors, content types                           */
/* -------------------------------------------------------------------------- */

export const sections = pgTable(
  'sections',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    siteId: uuid('site_id')
      .notNull()
      .references(() => sites.id, { onDelete: 'cascade' }),
    parentId: uuid('parent_id').references((): AnyPgColumn => sections.id, { onDelete: 'set null' }),
    name: text('name').notNull(),
    /** Unique per site; must not collide with reserved public routes. */
    slug: text('slug').notNull(),
    description: text('description'),
    /** Optional accent colour (hex) used by the public theme. */
    color: text('color'),
    sortOrder: integer('sort_order').notNull().default(0),
    showInMenu: boolean('show_in_menu').notNull().default(true),
    isActive: boolean('is_active').notNull().default(true),
    seoTitle: text('seo_title'),
    seoDescription: text('seo_description'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('sections_site_slug_idx').on(t.siteId, t.slug), index('sections_site_idx').on(t.siteId)],
);

export const tags = pgTable(
  'tags',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    siteId: uuid('site_id')
      .notNull()
      .references(() => sites.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    slug: text('slug').notNull(),
    description: text('description'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('tags_site_slug_idx').on(t.siteId, t.slug), index('tags_site_idx').on(t.siteId)],
);

/**
 * Bylines. An author may be linked to a user account, or be an external
 * freelancer / agency ("NTB") with no login.
 */
export const authors = pgTable(
  'authors',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    siteId: uuid('site_id')
      .notNull()
      .references(() => sites.id, { onDelete: 'cascade' }),
    userId: uuid('user_id').references(() => users.id, { onDelete: 'set null' }),
    name: text('name').notNull(),
    slug: text('slug').notNull(),
    /** Job title, e.g. "Journalist", "Ansvarlig redaktør". */
    title: text('title'),
    bio: text('bio'),
    email: text('email'),
    phone: text('phone'),
    imageMediaId: uuid('image_media_id'),
    isActive: boolean('is_active').notNull().default(true),
    sortOrder: integer('sort_order').notNull().default(0),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('authors_site_slug_idx').on(t.siteId, t.slug), index('authors_site_idx').on(t.siteId)],
);

/**
 * Flexible content types. Each site starts with `article`, `opinion`, `notice`
 * and may add its own, each with a list of custom field definitions rendered
 * generically by the editor.
 */
export const contentTypes = pgTable(
  'content_types',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    siteId: uuid('site_id')
      .notNull()
      .references(() => sites.id, { onDelete: 'cascade' }),
    /** Stable key, e.g. 'article', 'opinion', 'notice', 'obituary', 'event'. */
    key: text('key').notNull(),
    name: text('name').notNull(),
    description: text('description'),
    /** lucide icon name. */
    icon: text('icon'),
    /** Custom field definitions; see FieldDef in src/lib/validation/site.ts. */
    fields: jsonb('fields').$type<FieldDef[]>().notNull().default(sql`'[]'::jsonb`),
    /** Which public template renders it: 'article' | 'opinion' | 'notice' | 'longread'. */
    template: text('template').notNull().default('article'),
    /** Whether new articles default to this type. Exactly one per site. */
    isDefault: boolean('is_default').notNull().default(false),
    isActive: boolean('is_active').notNull().default(true),
    sortOrder: integer('sort_order').notNull().default(0),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('content_types_site_key_idx').on(t.siteId, t.key)],
);

/* -------------------------------------------------------------------------- */
/*  Media                                                                      */
/* -------------------------------------------------------------------------- */

export type MediaVariant = {
  /** Storage key relative to the storage root. */
  key: string;
  width: number;
  height: number;
  format: 'webp' | 'avif' | 'jpeg' | 'png' | 'gif';
  size: number;
};

export const media = pgTable(
  'media',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    siteId: uuid('site_id')
      .notNull()
      .references(() => sites.id, { onDelete: 'cascade' }),
    kind: mediaKindEnum('kind').notNull().default('image'),
    /** Original filename as uploaded. */
    filename: text('filename').notNull(),
    /** Storage key of the original, e.g. "2026/09/<uuid>.jpg". */
    storageKey: text('storage_key').notNull(),
    mime: text('mime').notNull(),
    size: integer('size').notNull(),
    width: integer('width'),
    height: integer('height'),
    /** Seconds, for audio/video. */
    duration: real('duration'),
    /** Required before an image can be used in a published article. */
    alt: text('alt'),
    caption: text('caption'),
    /** Photographer / agency, e.g. "Foto: Kari Nordmann". */
    credit: text('credit'),
    license: text('license'),
    sourceUrl: text('source_url'),
    /** Focal point, 0..1 from top-left. Defaults to centre. */
    focalX: real('focal_x').notNull().default(0.5),
    focalY: real('focal_y').notNull().default(0.5),
    /** Generated responsive variants keyed by width, e.g. { "640": {...} }. */
    variants: jsonb('variants').$type<Record<string, MediaVariant>>().notNull().default(sql`'{}'::jsonb`),
    /** Dominant colour (hex) for placeholders. */
    dominantColor: text('dominant_color'),
    /** Simple free-form grouping. */
    folder: text('folder'),
    tags: text('tags').array().notNull().default(sql`'{}'::text[]`),
    exif: jsonb('exif').$type<Record<string, unknown>>(),
    takenAt: timestamp('taken_at', { withTimezone: true }),
    uploadedBy: uuid('uploaded_by').references(() => users.id, { onDelete: 'set null' }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
  },
  (t) => [
    index('media_site_created_idx').on(t.siteId, t.createdAt),
    index('media_site_kind_idx').on(t.siteId, t.kind),
  ],
);

/* -------------------------------------------------------------------------- */
/*  Articles                                                                   */
/* -------------------------------------------------------------------------- */

export const articles = pgTable(
  'articles',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    siteId: uuid('site_id')
      .notNull()
      .references(() => sites.id, { onDelete: 'cascade' }),
    contentTypeId: uuid('content_type_id')
      .notNull()
      .references(() => contentTypes.id, { onDelete: 'restrict' }),
    sectionId: uuid('section_id').references(() => sections.id, { onDelete: 'set null' }),

    /** Stikktittel — small label above the title. */
    kicker: text('kicker'),
    title: text('title').notNull().default(''),
    /** Ingress. */
    lead: text('lead'),
    /** Unique per site. Generated from title with Norwegian transliteration. */
    slug: text('slug').notNull(),
    /** ProseMirror/TipTap document; see src/lib/content/types.ts. */
    body: jsonb('body').$type<ContentDoc>().notNull().default(sql`'{"type":"doc","content":[]}'::jsonb`),
    /** Plain-text projection of body, maintained by the article service. Used for search and excerpts. */
    bodyText: text('body_text').notNull().default(''),
    /** Values for the content type's custom fields, keyed by field key. */
    customFields: jsonb('custom_fields').$type<Record<string, unknown>>().notNull().default(sql`'{}'::jsonb`),

    status: articleStatusEnum('status').notNull().default('draft'),
    access: articleAccessEnum('access').notNull().default('open'),

    featuredMediaId: uuid('featured_media_id').references(() => media.id, { onDelete: 'set null' }),
    /** Optional per-article overrides of the media's caption/credit. */
    featuredCaption: text('featured_caption'),
    featuredCredit: text('featured_credit'),

    seoTitle: text('seo_title'),
    seoDescription: text('seo_description'),
    canonicalUrl: text('canonical_url'),
    noIndex: boolean('no_index').notNull().default(false),
    /** Marks a "Siste nytt"/breaking story for the front page and feeds. */
    isBreaking: boolean('is_breaking').notNull().default(false),
    /** Annonsørinnhold — must be labelled clearly (VVP / Markedsføringsloven). */
    isSponsored: boolean('is_sponsored').notNull().default(false),
    /** Disable comments/sharing UI etc. Reserved. */
    flags: jsonb('flags').$type<Record<string, boolean>>().notNull().default(sql`'{}'::jsonb`),

    publishedAt: timestamp('published_at', { withTimezone: true }),
    firstPublishedAt: timestamp('first_published_at', { withTimezone: true }),
    scheduledAt: timestamp('scheduled_at', { withTimezone: true }),
    unpublishedAt: timestamp('unpublished_at', { withTimezone: true }),

    /** Planning fields (redaksjonsplan). */
    assignedTo: uuid('assigned_to').references(() => users.id, { onDelete: 'set null' }),
    deadlineAt: timestamp('deadline_at', { withTimezone: true }),
    plannedAt: timestamp('planned_at', { withTimezone: true }),

    /** Soft edit lock with heartbeat. */
    lockedBy: uuid('locked_by').references(() => users.id, { onDelete: 'set null' }),
    lockedAt: timestamp('locked_at', { withTimezone: true }),

    wordCount: integer('word_count').notNull().default(0),
    readingTimeMin: integer('reading_time_min').notNull().default(0),
    /** Incremented on every saved revision. */
    version: integer('version').notNull().default(1),

    createdBy: uuid('created_by').references(() => users.id, { onDelete: 'set null' }),
    updatedBy: uuid('updated_by').references(() => users.id, { onDelete: 'set null' }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),

    /** Weighted Norwegian full-text search vector (generated column). */
    search: tsvector('search').generatedAlwaysAs(
      sql`setweight(to_tsvector('norwegian', coalesce(title, '')), 'A') || setweight(to_tsvector('norwegian', coalesce(kicker, '')), 'B') || setweight(to_tsvector('norwegian', coalesce(lead, '')), 'B') || setweight(to_tsvector('norwegian', coalesce(body_text, '')), 'C')`,
    ),
  },
  (t) => [
    uniqueIndex('articles_site_slug_idx').on(t.siteId, t.slug),
    index('articles_site_status_published_idx').on(t.siteId, t.status, t.publishedAt),
    index('articles_section_idx').on(t.sectionId),
    index('articles_site_updated_idx').on(t.siteId, t.updatedAt),
    index('articles_scheduled_idx').on(t.status, t.scheduledAt),
    index('articles_search_idx').using('gin', t.search),
  ],
);

export const articleTags = pgTable(
  'article_tags',
  {
    articleId: uuid('article_id')
      .notNull()
      .references(() => articles.id, { onDelete: 'cascade' }),
    tagId: uuid('tag_id')
      .notNull()
      .references(() => tags.id, { onDelete: 'cascade' }),
  },
  (t) => [primaryKey({ columns: [t.articleId, t.tagId] }), index('article_tags_tag_idx').on(t.tagId)],
);

export const articleBylines = pgTable(
  'article_bylines',
  {
    articleId: uuid('article_id')
      .notNull()
      .references(() => articles.id, { onDelete: 'cascade' }),
    authorId: uuid('author_id')
      .notNull()
      .references(() => authors.id, { onDelete: 'cascade' }),
    role: bylineRoleEnum('role').notNull().default('text'),
    sortOrder: integer('sort_order').notNull().default(0),
  },
  (t) => [primaryKey({ columns: [t.articleId, t.authorId] }), index('article_bylines_author_idx').on(t.authorId)],
);

export const articleRelated = pgTable(
  'article_related',
  {
    articleId: uuid('article_id')
      .notNull()
      .references(() => articles.id, { onDelete: 'cascade' }),
    relatedId: uuid('related_id')
      .notNull()
      .references(() => articles.id, { onDelete: 'cascade' }),
    sortOrder: integer('sort_order').notNull().default(0),
  },
  (t) => [primaryKey({ columns: [t.articleId, t.relatedId] })],
);

/** Full snapshot of the editable article fields at a point in time. */
export type ArticleSnapshot = {
  kicker: string | null;
  title: string;
  lead: string | null;
  slug: string;
  body: ContentDoc;
  customFields: Record<string, unknown>;
  sectionId: string | null;
  access: ArticleAccess;
  featuredMediaId: string | null;
  featuredCaption: string | null;
  featuredCredit: string | null;
  seoTitle: string | null;
  seoDescription: string | null;
  tagIds: string[];
  bylines: { authorId: string; role: BylineRole }[];
  isBreaking: boolean;
  isSponsored: boolean;
};

export const articleRevisions = pgTable(
  'article_revisions',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    articleId: uuid('article_id')
      .notNull()
      .references(() => articles.id, { onDelete: 'cascade' }),
    version: integer('version').notNull(),
    kind: revisionKindEnum('kind').notNull().default('manual'),
    snapshot: jsonb('snapshot').$type<ArticleSnapshot>().notNull(),
    note: text('note'),
    createdBy: uuid('created_by').references(() => users.id, { onDelete: 'set null' }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex('article_revisions_article_version_idx').on(t.articleId, t.version),
    index('article_revisions_article_idx').on(t.articleId, t.createdAt),
  ],
);

/** Internal editorial notes/comments on an article (never public). */
export const articleNotes = pgTable(
  'article_notes',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    articleId: uuid('article_id')
      .notNull()
      .references(() => articles.id, { onDelete: 'cascade' }),
    userId: uuid('user_id').references(() => users.id, { onDelete: 'set null' }),
    body: text('body').notNull(),
    resolvedAt: timestamp('resolved_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('article_notes_article_idx').on(t.articleId, t.createdAt)],
);

/** Daily view counters for "mest lest" — privacy-friendly, no PII. */
export const articleViews = pgTable(
  'article_views',
  {
    articleId: uuid('article_id')
      .notNull()
      .references(() => articles.id, { onDelete: 'cascade' }),
    day: date('day').notNull(),
    views: integer('views').notNull().default(0),
  },
  (t) => [primaryKey({ columns: [t.articleId, t.day] })],
);

/** Path redirects, auto-created when a published slug changes. */
export const redirects = pgTable(
  'redirects',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    siteId: uuid('site_id')
      .notNull()
      .references(() => sites.id, { onDelete: 'cascade' }),
    fromPath: text('from_path').notNull(),
    toPath: text('to_path').notNull(),
    statusCode: integer('status_code').notNull().default(301),
    hits: integer('hits').notNull().default(0),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('redirects_site_from_idx').on(t.siteId, t.fromPath)],
);

/* -------------------------------------------------------------------------- */
/*  Layouts and menus (front page composition)                                 */
/* -------------------------------------------------------------------------- */

export const layouts = pgTable(
  'layouts',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    siteId: uuid('site_id')
      .notNull()
      .references(() => sites.id, { onDelete: 'cascade' }),
    /** 'front' for the front page, 'section:<sectionId>' for section pages. */
    key: text('key').notNull(),
    name: text('name').notNull(),
    /** Work-in-progress layout, edited in the admin. */
    draft: jsonb('draft').$type<LayoutDoc>().notNull().default(sql`'{"version":1,"rows":[]}'::jsonb`),
    /** What the public site renders. */
    published: jsonb('published').$type<LayoutDoc>(),
    publishedAt: timestamp('published_at', { withTimezone: true }),
    updatedBy: uuid('updated_by').references(() => users.id, { onDelete: 'set null' }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('layouts_site_key_idx').on(t.siteId, t.key)],
);

export const menus = pgTable(
  'menus',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    siteId: uuid('site_id')
      .notNull()
      .references(() => sites.id, { onDelete: 'cascade' }),
    /** 'primary' | 'footer' | 'topbar'. */
    key: text('key').notNull(),
    items: jsonb('items').$type<MenuItem[]>().notNull().default(sql`'[]'::jsonb`),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('menus_site_key_idx').on(t.siteId, t.key)],
);

/* -------------------------------------------------------------------------- */
/*  Live blogs (direktestudio)                                                 */
/* -------------------------------------------------------------------------- */

export const liveBlogs = pgTable(
  'live_blogs',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    siteId: uuid('site_id')
      .notNull()
      .references(() => sites.id, { onDelete: 'cascade' }),
    /** Optional: the live blog is embedded in / linked from this article. */
    articleId: uuid('article_id').references(() => articles.id, { onDelete: 'set null' }),
    title: text('title').notNull(),
    slug: text('slug').notNull(),
    description: text('description'),
    status: liveBlogStatusEnum('status').notNull().default('draft'),
    startedAt: timestamp('started_at', { withTimezone: true }),
    endedAt: timestamp('ended_at', { withTimezone: true }),
    createdBy: uuid('created_by').references(() => users.id, { onDelete: 'set null' }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('live_blogs_site_slug_idx').on(t.siteId, t.slug)],
);

export const livePosts = pgTable(
  'live_posts',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    liveBlogId: uuid('live_blog_id')
      .notNull()
      .references(() => liveBlogs.id, { onDelete: 'cascade' }),
    title: text('title'),
    body: jsonb('body').$type<ContentDoc>().notNull(),
    authorId: uuid('author_id').references(() => authors.id, { onDelete: 'set null' }),
    isPinned: boolean('is_pinned').notNull().default(false),
    /** Nøkkelhendelse — shown in the summary list. */
    isKeyEvent: boolean('is_key_event').notNull().default(false),
    publishedAt: timestamp('published_at', { withTimezone: true }).notNull().defaultNow(),
    createdBy: uuid('created_by').references(() => users.id, { onDelete: 'set null' }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
  },
  (t) => [index('live_posts_blog_published_idx').on(t.liveBlogId, t.publishedAt)],
);

/* -------------------------------------------------------------------------- */
/*  Integrations: webhooks, audit log, notifications                           */
/* -------------------------------------------------------------------------- */

export const webhooks = pgTable(
  'webhooks',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    siteId: uuid('site_id')
      .notNull()
      .references(() => sites.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    url: text('url').notNull(),
    /** HMAC-SHA256 signing secret. */
    secret: text('secret').notNull(),
    /** e.g. ['article.published', 'article.updated', 'article.unpublished', 'layout.published']. */
    events: text('events').array().notNull().default(sql`'{}'::text[]`),
    isActive: boolean('is_active').notNull().default(true),
    createdBy: uuid('created_by').references(() => users.id, { onDelete: 'set null' }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('webhooks_site_idx').on(t.siteId)],
);

export const webhookDeliveries = pgTable(
  'webhook_deliveries',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    webhookId: uuid('webhook_id')
      .notNull()
      .references(() => webhooks.id, { onDelete: 'cascade' }),
    event: text('event').notNull(),
    payload: jsonb('payload').$type<Record<string, unknown>>().notNull(),
    attempts: integer('attempts').notNull().default(0),
    /** Null until delivered. */
    deliveredAt: timestamp('delivered_at', { withTimezone: true }),
    nextAttemptAt: timestamp('next_attempt_at', { withTimezone: true }).notNull().defaultNow(),
    lastStatusCode: integer('last_status_code'),
    lastError: text('last_error'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('webhook_deliveries_pending_idx').on(t.deliveredAt, t.nextAttemptAt)],
);

export const auditLog = pgTable(
  'audit_log',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    siteId: uuid('site_id').references(() => sites.id, { onDelete: 'cascade' }),
    userId: uuid('user_id').references(() => users.id, { onDelete: 'set null' }),
    /** Dotted action name, e.g. 'article.publish', 'user.invite', 'settings.update'. */
    action: text('action').notNull(),
    entityType: text('entity_type'),
    entityId: uuid('entity_id'),
    /** Human-readable summary plus optional structured diff. */
    summary: text('summary'),
    data: jsonb('data').$type<Record<string, unknown>>(),
    ip: text('ip'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('audit_log_site_created_idx').on(t.siteId, t.createdAt),
    index('audit_log_entity_idx').on(t.entityType, t.entityId),
  ],
);

export const notifications = pgTable(
  'notifications',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    siteId: uuid('site_id').references(() => sites.id, { onDelete: 'cascade' }),
    /** e.g. 'article.assigned', 'article.note', 'article.published', 'article.review_requested'. */
    kind: text('kind').notNull(),
    title: text('title').notNull(),
    body: text('body'),
    /** Admin-relative link, e.g. '/admin/artikler/<id>'. */
    link: text('link'),
    readAt: timestamp('read_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('notifications_user_idx').on(t.userId, t.readAt, t.createdAt)],
);

/* -------------------------------------------------------------------------- */
/*  Relations (for db.query.* relational API)                                  */
/* -------------------------------------------------------------------------- */

export const sitesRelations = relations(sites, ({ many }) => ({
  memberships: many(memberships),
  sections: many(sections),
  tags: many(tags),
  authors: many(authors),
  contentTypes: many(contentTypes),
  articles: many(articles),
  media: many(media),
  layouts: many(layouts),
  menus: many(menus),
}));

export const usersRelations = relations(users, ({ many }) => ({
  memberships: many(memberships),
  sessions: many(sessions),
  notifications: many(notifications),
}));

export const membershipsRelations = relations(memberships, ({ one }) => ({
  user: one(users, { fields: [memberships.userId], references: [users.id] }),
  site: one(sites, { fields: [memberships.siteId], references: [sites.id] }),
}));

export const sessionsRelations = relations(sessions, ({ one }) => ({
  user: one(users, { fields: [sessions.userId], references: [users.id] }),
}));

export const sectionsRelations = relations(sections, ({ one, many }) => ({
  site: one(sites, { fields: [sections.siteId], references: [sites.id] }),
  parent: one(sections, { fields: [sections.parentId], references: [sections.id], relationName: 'section_parent' }),
  children: many(sections, { relationName: 'section_parent' }),
  articles: many(articles),
}));

export const tagsRelations = relations(tags, ({ many }) => ({
  articleTags: many(articleTags),
}));

export const authorsRelations = relations(authors, ({ one, many }) => ({
  user: one(users, { fields: [authors.userId], references: [users.id] }),
  image: one(media, { fields: [authors.imageMediaId], references: [media.id] }),
  bylines: many(articleBylines),
}));

export const contentTypesRelations = relations(contentTypes, ({ many }) => ({
  articles: many(articles),
}));

export const mediaRelations = relations(media, ({ one }) => ({
  site: one(sites, { fields: [media.siteId], references: [sites.id] }),
  uploader: one(users, { fields: [media.uploadedBy], references: [users.id] }),
}));

export const articlesRelations = relations(articles, ({ one, many }) => ({
  site: one(sites, { fields: [articles.siteId], references: [sites.id] }),
  contentType: one(contentTypes, { fields: [articles.contentTypeId], references: [contentTypes.id] }),
  section: one(sections, { fields: [articles.sectionId], references: [sections.id] }),
  featuredMedia: one(media, { fields: [articles.featuredMediaId], references: [media.id] }),
  creator: one(users, { fields: [articles.createdBy], references: [users.id], relationName: 'article_creator' }),
  updater: one(users, { fields: [articles.updatedBy], references: [users.id], relationName: 'article_updater' }),
  assignee: one(users, { fields: [articles.assignedTo], references: [users.id], relationName: 'article_assignee' }),
  locker: one(users, { fields: [articles.lockedBy], references: [users.id], relationName: 'article_locker' }),
  articleTags: many(articleTags),
  bylines: many(articleBylines),
  revisions: many(articleRevisions),
  notes: many(articleNotes),
  related: many(articleRelated, { relationName: 'article_related_from' }),
}));

export const articleTagsRelations = relations(articleTags, ({ one }) => ({
  article: one(articles, { fields: [articleTags.articleId], references: [articles.id] }),
  tag: one(tags, { fields: [articleTags.tagId], references: [tags.id] }),
}));

export const articleBylinesRelations = relations(articleBylines, ({ one }) => ({
  article: one(articles, { fields: [articleBylines.articleId], references: [articles.id] }),
  author: one(authors, { fields: [articleBylines.authorId], references: [authors.id] }),
}));

export const articleRelatedRelations = relations(articleRelated, ({ one }) => ({
  article: one(articles, {
    fields: [articleRelated.articleId],
    references: [articles.id],
    relationName: 'article_related_from',
  }),
  related: one(articles, {
    fields: [articleRelated.relatedId],
    references: [articles.id],
    relationName: 'article_related_to',
  }),
}));

export const articleRevisionsRelations = relations(articleRevisions, ({ one }) => ({
  article: one(articles, { fields: [articleRevisions.articleId], references: [articles.id] }),
  author: one(users, { fields: [articleRevisions.createdBy], references: [users.id] }),
}));

export const articleNotesRelations = relations(articleNotes, ({ one }) => ({
  article: one(articles, { fields: [articleNotes.articleId], references: [articles.id] }),
  user: one(users, { fields: [articleNotes.userId], references: [users.id] }),
}));

export const liveBlogsRelations = relations(liveBlogs, ({ one, many }) => ({
  site: one(sites, { fields: [liveBlogs.siteId], references: [sites.id] }),
  article: one(articles, { fields: [liveBlogs.articleId], references: [articles.id] }),
  posts: many(livePosts),
}));

export const livePostsRelations = relations(livePosts, ({ one }) => ({
  liveBlog: one(liveBlogs, { fields: [livePosts.liveBlogId], references: [liveBlogs.id] }),
  author: one(authors, { fields: [livePosts.authorId], references: [authors.id] }),
}));

export const webhooksRelations = relations(webhooks, ({ many }) => ({
  deliveries: many(webhookDeliveries),
}));

export const webhookDeliveriesRelations = relations(webhookDeliveries, ({ one }) => ({
  webhook: one(webhooks, { fields: [webhookDeliveries.webhookId], references: [webhooks.id] }),
}));

export const notificationsRelations = relations(notifications, ({ one }) => ({
  user: one(users, { fields: [notifications.userId], references: [users.id] }),
}));

/* -------------------------------------------------------------------------- */
/*  Inferred row types                                                         */
/* -------------------------------------------------------------------------- */

export type Site = typeof sites.$inferSelect;
export type NewSite = typeof sites.$inferInsert;
export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type Membership = typeof memberships.$inferSelect;
export type Session = typeof sessions.$inferSelect;
export type AuthToken = typeof authTokens.$inferSelect;
export type ApiKey = typeof apiKeys.$inferSelect;
export type Section = typeof sections.$inferSelect;
export type NewSection = typeof sections.$inferInsert;
export type Tag = typeof tags.$inferSelect;
export type Author = typeof authors.$inferSelect;
export type NewAuthor = typeof authors.$inferInsert;
export type ContentType = typeof contentTypes.$inferSelect;
export type Media = typeof media.$inferSelect;
export type NewMedia = typeof media.$inferInsert;
export type Article = typeof articles.$inferSelect;
export type NewArticle = typeof articles.$inferInsert;
export type ArticleRevision = typeof articleRevisions.$inferSelect;
export type ArticleNote = typeof articleNotes.$inferSelect;
export type Redirect = typeof redirects.$inferSelect;
export type Layout = typeof layouts.$inferSelect;
export type Menu = typeof menus.$inferSelect;
export type LiveBlog = typeof liveBlogs.$inferSelect;
export type LivePost = typeof livePosts.$inferSelect;
export type Webhook = typeof webhooks.$inferSelect;
export type WebhookDelivery = typeof webhookDeliveries.$inferSelect;
export type AuditEntry = typeof auditLog.$inferSelect;
export type Notification = typeof notifications.$inferSelect;
